import os

filepath = '/home/jmolmo/git/colabedu/ce-web/apps/colabedu-net/src/pages/en/government.astro'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    'Inteligencia Pedagógica Global': 'Global Pedagogical Intelligence',
    'Califica menos.<br/><span class="text-primary underline decoration-indigo-200 decoration-8">Enseña más.</span>': 'Grade less.<br/><span class="text-primary underline decoration-indigo-200 decoration-8">Teach more.</span>',
    'Libérate de la carga administrativa. Nuestra IA califica audios, manuscritos y textos con precisión del 99%.': 'Free yourself from the administrative burden. Our AI grades audio, handwritten assignments, and texts with 99% accuracy.',
    'Ahorro de Tiempo Real': 'Real Time Savings',
    'Reduce el tiempo de corrección de 15 horas a 3 horas semanales. Visualiza el impacto acumulado en un semestre lectivo.': 'Reduce grading time from 15 hours to 3 hours a week. Visualize the accumulated impact over an academic semester.',
    'Funcionalidades Anti-Burnout': 'Anti-Burnout Features',
    'OCR de Manuscritos': 'Handwriting OCR',
    'Interpretación experta de caligrafía difícil y evaluación inmediata.': 'Expert interpretation of difficult handwriting and immediate evaluation.',
    'Orales One-Shot': 'One-Shot Orals',
    'Transcripción y calificación de fluidez y contenido en un solo paso.': 'Transcription and grading of fluency and content in a single step.',
    'Diseñador de Rúbricas': 'Rubric Designer',
    'Generación dinámica de criterios alineados a estándares internacionales.': 'Dynamic generation of criteria aligned to international standards.',
    'Integración LMS Invisible': 'Invisible LMS Integration',
    'Grade Passback automático a Canvas, Classroom y Moodle.': 'Automatic Grade Passback to Canvas, Classroom, and Moodle.',
    'Pedagogía de 3 Fases': '3-Phase Pedagogy',
    'Práctica Socrática': 'Socratic Practice',
    'Prueba Blindada': 'Shielded Test',
    'Revisión Docente': 'Teacher Review',
    'Recupera tu vida personal hoy.': 'Reclaim your personal life today.',
    'Empezar ahora': 'Start now',
    'Estandarización y <br/><span class="text-primary italic text-6xl">Justicia Académica.</span>': 'Standardization and <br/><span class="text-primary italic text-6xl">Academic Justice.</span>',
    'Elimine la deriva pedagógica. Asegure que cada profesor de su institución evalúe con el mismo rigor y calidad de feedback.': 'Eliminate pedagogical drift. Ensure that every teacher in your institution grades with the same rigor and feedback quality.',
    'Consistencia Evaluativa (Humano vs IA)': 'Grading Consistency (Human vs AI)',
    'Impacto en la Equidad': 'Impact on Equity',
    'La varianza subjetiva entre docentes es el mayor riesgo para la equidad estudiantil. ColabEdu implementa un motor determinista que garantiza la misma vara de medir para todos.': 'Subjective variance among teachers is the biggest risk to student equity. ColabEdu implements a deterministic engine that guarantees the same measuring stick for everyone.',
    'Integración LTI 1.3 Advantage': 'LTI 1.3 Advantage Integration',
    'Sincronización profunda de grado institucional. Sus datos permanecen seguros y soberanos dentro de su infraestructura actual.': 'Deep institutional-grade synchronization. Your data remains secure and sovereign within your current infrastructure.',
    'Seguridad Nivel Enterprise': 'Enterprise-Level Security',
    'Consola para Coordinadores': 'Coordinator Console',
    'Visualice el rendimiento por departamento en tiempo real, sin pedir informes adicionales a los docentes.': 'Visualize department performance in real time, without asking teachers for additional reports.',
    'Analítica de Brechas': 'Gap Analytics',
    'Detección de Abandono': 'Dropout Detection',
    'Gobernanza Curricular': 'Curricular Governance',
    '"La estandarización de criterios en nuestro departamento de idiomas mejoró un 40% en el primer trimestre."': '"The standardization of criteria in our language department improved by 40% in the first quarter."',
    'Escale la excelencia institucional.': 'Scale institutional excellence.',
    'Agendar Demo': 'Schedule Demo',
    'Revitalice su <br/><span class="gradient-text-publisher italic">IP Editorial.</span>': 'Revitalize your <br/><span class="gradient-text-publisher italic">Editorial IP.</span>',
    'No venda archivos muertos. Convierta su catálogo en una red de tutores inteligentes que protegen su IP mediante referencialidad ciega.': 'Don\'t sell dead files. Turn your catalog into a network of intelligent tutors that protect your IP through blind referentiality.',
    'Ciclo de Vida Activo': 'Active Lifecycle',
    'Mapeamos el uso del contenido tradicional frente a la versión enriquecida con IA Socrática. El engagement aumenta un 60%.': 'We mapped the use of traditional content versus the version enriched with Socratic AI. Engagement increases by 60%.',
    'La Factoría de Contenidos': 'The Content Factory',
    'Atomización RAG': 'RAG Atomization',
    'Transformamos PDFs en grafos de conocimiento estructurados.': 'We transform PDFs into structured knowledge graphs.',
    'Mutación Instruccional': 'Instructional Mutation',
    'De texto pasivo a debates y simulaciones automáticas.': 'From passive text to automatic debates and simulations.',
    'Tagging Normativo': 'Normative Tagging',
    'Alineación con decretos oficiales LOMLOE/SEP/AP.': 'Alignment with official LOMLOE/SEP/AP decrees.',
    'Referencialidad Ciega': 'Blind Referentiality',
    '"La IA guía al alumno a consultar su libro físico en pasajes clave, protegiendo las ventas y validando el uso del manual oficial."': '"The AI guides the student to consult their physical book in key passages, protecting sales and validating the use of the official manual."',
    'Nuevos Modelos de Monetización': 'New Monetization Models',
    'Pasa de la venta única a licencias de "Capa de Inteligencia" por estudiante/año.': 'Move from one-time sales to "Intelligence Layer" licenses per student/year.',
    'Modernice su catálogo en 15 días.': 'Modernize your catalog in 15 days.',
    'Hablar con Estrategia': 'Talk to Strategy',
    'Aprende, <br/><span class="text-secondary italic">no atajes.</span>': 'Learn, <br/><span class="text-secondary italic">don\'t shortcut.</span>',
    'ColabEdu es tu tutor privado disponible 24/7 que no te da la respuesta, sino que te enseña a encontrarla.': 'ColabEdu is your private tutor available 24/7 that doesn\'t give you the answer, but teaches you how to find it.',
    'Tu Velocidad de Aprendizaje': 'Your Learning Speed',
    'El Gimnasio del Aprendizaje': 'The Learning Gym',
    'Practica en un entorno libre de estrés. Nuestra IA detecta donde te bloqueas y te da la pista exacta que necesitas para superar el reto.': 'Practice in a stress-free environment. Our AI detects where you get stuck and gives you the exact hint you need to overcome the challenge.',
    'Feedback Instantáneo': 'Instant Feedback',
    'No esperes semanas. Recibe correcciones gramaticales y sugerencias de contenido en el momento de mayor curiosidad.': 'Don\'t wait weeks. Receive grammatical corrections and content suggestions at the moment of highest curiosity.',
    'Entrenamiento Oral': 'Oral Training',
    'Graba tu voz y obtén diagnósticos de fluidez inmediatos para mejorar antes del examen real.': 'Record your voice and get immediate fluency diagnostics to improve before the real exam.',
    'Andamiaje Inteligente': 'Intelligent Scaffolding',
    'Nivelamos el contenido a tu capacidad actual para que el progreso sea constante y motivador.': 'We level the content to your current capacity so that progress is constant and motivating.',
    'Gana Medallas de Maestría': 'Earn Mastery Badges',
    'Conviértete en el dueño de tu progreso.': 'Become the master of your progress.',
    'Acceder a mi Portal': 'Access my Portal',
    'Analítica de <br/><span class="gradient-text-gov">Impacto Nacional.</span>': 'Analytics of <br/><span class="gradient-text-gov">National Impact.</span>',
    'Infraestructura de datos para el cumplimiento curricular y la toma de decisiones basada en evidencias de aula en tiempo real.': 'Data infrastructure for curricular compliance and decision making based on real-time classroom evidence.',
    'Cumplimiento de Competencias por Región (%)': 'Competency Compliance by Region (%)',
    'Soberanía de Datos': 'Data Sovereignty',
    'Modelos de IA alojados localmente con cumplimiento absoluto de leyes nacionales de privacidad.': 'Locally hosted AI models with absolute compliance with national privacy laws.',
    'Pilares Gubernamentales': 'Governmental Pillars',
    'Mapeo automático de notas a Decretos Reales (LOMLOE) o estándares estatales (TEKS).': 'Automatic mapping of grades to Royal Decrees (LOMLOE) or state standards (TEKS).',
    'Equidad Digital': 'Digital Equity',
    'Mismos criterios de alta calidad para la escuela rural y la metropolitana.': 'Same high-quality criteria for rural and metropolitan schools.',
    'Detección Precoz': 'Early Detection',
    'Alertas tempranas de brechas de aprendizaje antes de las pruebas estatales.': 'Early warnings of learning gaps before state tests.',
    'Respuesta a la Crisis de Personal': 'Response to the Staffing Crisis',
    'La UNESCO estima una necesidad de 44M de docentes. ColabEdu multiplica la eficiencia del docente actual, permitiendo gestionar sistemas masivos sin pérdida de calidad.': 'UNESCO estimates a need for 44M teachers. ColabEdu multiplies the efficiency of current teachers, allowing massive systems to be managed without loss of quality.',
    'Carga Administrativa': 'Administrative Load',
    'Seguridad Soberana': 'Sovereign Security',
    'Lidere la transformación pública de la educación.': 'Lead the public transformation of education.',
    'Contactar Asuntos Públicos': 'Contact Public Affairs',
    'Protección de Propiedad Intelectual y Soberanía de Datos.': 'Intellectual Property Protection and Data Sovereignty.',
    "'Sin ColabEdu', 'Con ColabEdu'": "'Without ColabEdu', 'With ColabEdu'",
    "'Corrección Humana'": "'Human Grading'",
    "'ColabEdu IA'": "'ColabEdu AI'",
    "'Lectura PDF'": "'PDF Reading'",
    "'Tutor IA'": "'AI Tutor'",
    "'Día 1', 'Día 7', 'Día 14', 'Día 30'": "'Day 1', 'Day 7', 'Day 14', 'Day 30'",
    "'Inicio', 'Semana 2', 'Semana 4', 'Maestría'": "'Start', 'Week 2', 'Week 4', 'Mastery'",
    "'Curva con Tutor IA'": "'Curve with AI Tutor'",
    "'Región A', 'Región B', 'Región C'": "'Region A', 'Region B', 'Region C'",
    "'Dominio Estándares Nacionales'": "'National Standards Mastery'"
}

for es_text, en_text in replacements.items():
    content = content.replace(es_text, en_text)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Translated {filepath}")
